sudo: required
services:
 - docker

script:
 - docker build -t isunix1/node .
 - docker images isunix1/node


before_deploy:
 - docker login -u isunix1 -p dockertest1

deploy:
  provider: script
  script: docker push isunix1/node
  on:
    branch: master

